### ISSUE TITLE
Don't delete trimmed reads, we need them!

### ISSUE THREAD

**Issue by johnsolk** [dib-lab/eel-pond#20]
In `1-quality.rst`, don't `rm *.fastq.gz` after interleaving. We will need these later for transrate and salmon.

**Comment by ctb** [comment]
Those are the raw reads and we aren't deleting them - they are linked from ../data/, right?

--
Titus Brown, ctbrown@ucdavis.edu

**Comment by johnsolk** [comment]
Ah, ok nevermind. Trimmed reads are `.qc.fq.gz` in `/mnt/work/quality`
